### ISSUE TITLE
Menu issue

### ISSUE THREAD

**Issue by ghost** [tegansnyder/JQuery-Mobile-Slide-Menu#1]
Hey Tegan,

The container now resizes correctly, tested on my iphone too :)

There's one other small issue with the menu, check out http://neilberry.com/app2/

I've added another page to your app as an example.  Click on Activity and this page will open correctly.

However, clicking on the menu icon again doesn't work, any ideas how we can get it working?

Thanks
Neil

**Comment by ghost** [comment]
Let me know if you want me to test anything ;)

**Comment by tegansnyder** [comment]
This is now fixed. I updated the click handler, added a event for stopping propagation.

``` javascript
$(document).on("click", ":jqmData(slidemenu)", function(event) {
        event.stopImmediatePropagation();
        slidemenu(sm);
});
```

**Comment by linuxonrails** [comment]
The problem is not fixed :-(
