### ISSUE TITLE
Different slide menus are not possible on multi-page

### ISSUE THREAD

**Issue by joanscript** [tegansnyder/JQuery-Mobile-Slide-Menu#5]
It would be great to have different slide menu depending on the page you are. For example: 
# page1 -> #slidemenu1
# page2 -> #slidemenu2

... 

But  even though you define different slide menus, all the pages uses the same as the first page. (#slidemenu1 following the example).
Is it there any way to solve this issue?

Thanks

**Comment by leonardoeloy** [comment]
I'm also facing the same issue. Will try to work on that...

**Comment by leonardoeloy** [comment]
So, this did the trick:

``` javascript
    $(document).on("click", ":jqmData(slidemenu)", function(event) {
        event.stopImmediatePropagation();
        slidemenu(sm);
        return false;
    });
    $(document).on("click", "a:not(:jqmData(slidemenu))", function(e) {
        only_close = true;
        slidemenu(sm, only_close);
        return false;
    });
```

You just need to tell jQuery to stop propagating the events to the browser. Didn't notice any immediate side effects of this solution, so I guess this is it.

Hopefully I'll send a pull request anytime soon! :)

**Comment by joanscript** [comment]
hi leonardoeloy, your solution didn't work for me. 
The problem on the plugin is that doing var sm = $($(":jqmData(slidemenu)").data('slidemenu')); only the data-slidemenu of the first will be selected. My proposal to have use different slide menus is:

```
    $(document).on("swipeleft",":jqmData(role='page')", function(event) {
            page = $.mobile.activePage.attr("id");
            var sm = $($("#"+page+" :jqmData(slidemenu)").data('slidemenu'));
            sm.addClass('slidemenu');
            only_close = true;
            slidemenu(sm, only_close);
            event.stopImmediatePropagation();
            event.preventDefault();
    });
```

And the same for all the events that work with the slidemenu.

**Comment by tegansnyder** [comment]
Please try the latest code. I updated it to include support for multiple pages, ajax, and multiple slide menus.
